const KEYS = {
  kyc_id: "kyc_id",
  user_id: "user_id",
  profile_image_id: "profile_image_id",
  //   kyc_approved_by: "approved_by",
  kyc_approved_by: "kyc_approved_by",
  nickname: "nickname",
  firstname: "firstname",
  lastname: "lastname",
  gender: "gender",
  dob: "dob",
  country_code: "country_code",
  mobile_no: "mobile_no",
  country: "country_id",
  city: "city",
  street: "street",
  state: "state",
  zip: "zip",
  tax_no: "tax_no",
  //   kyc_status: "kyc_status",
  status: "status",
  kyc_level: "kyc_level",
  kyc_source: "kyc_source",
  mobile_no_verified_at: "mobile_no_verified_at",
  submitted_at: "submitted_at",
  approved_at: "approved_at",
  declined_at: "declined_at",
  reason_for_decline: "reason_for_decline",
  profile_pic_path: "profile_pic_path",
  created_at: "created_at",
  updated_at: "updated_at",
};

module.exports = { KEYS };
